import type { TaskArchiveItem, TaskVersionRecord } from '../types/taskArchive';

function vid(t: string, v: string) { return `${t}-${v}`; }

function makePlanVersion(id: string, label: string, reason: string): TaskVersionRecord {
  return { versionId: vid(id, `plan-${label}`), label, kind: 'task_plan', reason, createdAt: `2026-04-27 1${4 + Number(label.slice(1))}:00`, status: 'archived', summary: '任务计划版本' };
}

function makeEvidenceVersion(id: string, label: string, reason: string): TaskVersionRecord {
  return { versionId: vid(id, `ev-${label}`), label, kind: 'evidence_pack', reason, createdAt: `2026-04-27 1${5 + Number(label.slice(1))}:30`, status: 'archived', summary: '证据资料版本' };
}

function makeOutputVersion(id: string, label: string, reason: string, failed = false): TaskVersionRecord {
  return { versionId: vid(id, `out-${label}`), label, kind: 'output', reason, createdAt: `2026-04-28 0${2 + Number(label.slice(1))}:00`, status: failed ? 'failed' : 'archived', failureReason: failed ? '模型调用返回空响应' : undefined, summary: failed ? '生成失败' : '输出版本' };
}


export const MOCK_TASKS: TaskArchiveItem[] = [
  {
    taskId: 't-completed',
    taskTitle: '分析 XX 半导体客户的应用工序',
    taskType: 'full_workflow',
    status: 'completed',
    recentStep: 'Output 生成完成',
    assistantName: '默认销售支持助手',
    updatedAt: '2026-04-28 14:00',
    taskGoal: '分析这家半导体材料客户的背景，检索行业涂布工艺案例，生成一份销售跟进方案。',
    planVersions: [makePlanVersion('t-completed', 'v2', '补充公司信息后更新'), makePlanVersion('t-completed', 'v1', '初始计划')],
    evidencePackVersions: [makeEvidenceVersion('t-completed', 'v2', '补充证据后更新'), makeEvidenceVersion('t-completed', 'v1', '初始检索')],
    outputVersions: [makeOutputVersion('t-completed', 'v3', '调整为简洁语气'), makeOutputVersion('t-completed', 'v2', '补充资料后重新生成'), makeOutputVersion('t-completed', 'v1', '首次生成')],
    analysisSummary: '识别为销售跟进场景，客户行业为半导体材料，建议输出正式跟进方案。',
    evidenceSummary: '已整理 3 条依据：行业涂布工艺标准、同类客户案例、产品技术参数对比。',
    risks: [{ level: 'info', title: '输出对象未指定', description: '未指定输出对象，默认使用通用销售沟通风格。' }],
    executionContext: { assistantName: '默认销售支持助手', modelName: 'gpt-4o-mini', dataSources: [{ name: '本地知识库', status: 'healthy' }, { name: '企查查', status: 'healthy' }], taskPlanner: { status: 'ready', source: 'embedded_model' } },
    completedSteps: ['分析客户场景', '检索资料与证据', '生成输出', '保存历史任务'],
    pendingSteps: [],
    hasOutput: true,
  },
  {
    taskId: 't-continuable',
    taskTitle: '检索锂电池涂布工艺案例',
    taskType: 'evidence_search',
    status: 'continuable',
    recentStep: 'Evidence 完成，待生成 Output',
    assistantName: '默认销售支持助手',
    updatedAt: '2026-04-28 12:30',
    taskGoal: '检索近期关于锂电池涂布工艺的行业案例和最佳实践。',
    planVersions: [makePlanVersion('t-continuable', 'v1', '初始计划')],
    evidencePackVersions: [makeEvidenceVersion('t-continuable', 'v1', '初始检索')],
    outputVersions: [],
    analysisSummary: '检索任务：锂电涂布工艺，行业案例方向。',
    evidenceSummary: '已整理 2 条依据：锂电涂布工艺案例、行业最佳实践。',
    risks: [{ level: 'warning', title: 'Output 尚未生成', description: 'Evidence 步骤已完成，可继续生成 Output。' }],
    executionContext: { assistantName: '默认销售支持助手', modelName: 'gpt-4o-mini', dataSources: [{ name: '本地知识库', status: 'healthy' }], taskPlanner: { status: 'ready', source: 'embedded_model' } },
    completedSteps: ['分析客户场景', '检索资料与证据'],
    pendingSteps: ['生成输出', '保存历史任务'],
    hasOutput: false,
  },
  {
    taskId: 't-failed-external',
    taskTitle: '分析新材料客户并生成方案',
    taskType: 'full_workflow',
    status: 'failed',
    recentStep: 'Evidence 失败',
    assistantName: '默认销售支持助手',
    updatedAt: '2026-04-28 11:00',
    taskGoal: '分析客户背景，生成销售支持方案。',
    planVersions: [makePlanVersion('t-failed-external', 'v1', '初始计划')],
    evidencePackVersions: [],
    outputVersions: [],
    analysisSummary: '分析完成：识别为销售跟进场景。',
    evidenceSummary: 'Evidence 步骤失败。',
    risks: [{ level: 'danger', title: '外部源不可用', description: '企查查连接中断，Evidence 步骤未完成。' }],
    executionContext: { assistantName: '默认销售支持助手', modelName: 'gpt-4o-mini', dataSources: [{ name: '本地知识库', status: 'healthy' }, { name: '企查查', status: 'unavailable' }], taskPlanner: { status: 'ready', source: 'embedded_model' } },
    failedStep: '检索资料与证据',
    failureKind: 'external_source',
    failureReason: '企查查连接中断，无法获取企业工商信息。',
    completedSteps: ['分析客户场景'],
    pendingSteps: ['检索资料与证据', '生成输出', '保存历史任务'],
    hasOutput: false,
  },
  {
    taskId: 't-failed-external-strong',
    taskTitle: '企业背景深度分析与风控报告',
    taskType: 'full_workflow',
    status: 'failed',
    recentStep: 'Evidence 失败',
    assistantName: '默认销售支持助手',
    updatedAt: '2026-04-28 10:30',
    taskGoal: '对该客户进行企业背景深度分析，生成风控报告。需要企查查数据支持经营风险评估。',
    planVersions: [makePlanVersion('t-failed-external-strong', 'v1', '初始计划')],
    evidencePackVersions: [],
    outputVersions: [],
    analysisSummary: '分析完成：风控场景，强依赖外部企业数据。',
    evidenceSummary: 'Evidence 步骤失败，企查查不可用。',
    risks: [{ level: 'danger', title: '强依赖外部源', description: '该任务需要企查查提供企业背景数据进行风险评估，外部源不可用导致无法继续。' }],
    executionContext: { assistantName: '默认销售支持助手', modelName: 'gpt-4o-mini', dataSources: [{ name: '本地知识库', status: 'healthy' }, { name: '企查查', status: 'unavailable' }], taskPlanner: { status: 'degraded', source: 'fallback' } },
    failedStep: '检索资料与证据',
    failureKind: 'external_source',
    failureReason: '企查查数据不可用，该任务需要外部企业数据进行风险评估。',
    completedSteps: ['分析客户场景'],
    pendingSteps: ['检索资料与证据', '生成输出', '保存历史任务'],
    hasOutput: false,
  },
  {
    taskId: 't-running',
    taskTitle: '生成 PCB 客户技术支持方案',
    taskType: 'output_generation',
    status: 'running',
    recentStep: 'Output 生成中',
    assistantName: '默认销售支持助手',
    updatedAt: '2026-04-28 15:00',
    taskGoal: '根据之前的 PCB 客户分析，生成技术支持方案。',
    planVersions: [makePlanVersion('t-running', 'v1', '初始计划')],
    evidencePackVersions: [makeEvidenceVersion('t-running', 'v1', '初始检索')],
    outputVersions: [{ versionId: vid('t-running', 'out-v1'), label: 'v1', kind: 'output', reason: '初次生成', createdAt: '2026-04-28 15:00', status: 'active' }],
    analysisSummary: 'PCB 行业客户，需要技术支持方案。',
    evidenceSummary: '已整理 2 条依据。',
    risks: [],
    executionContext: { assistantName: '默认销售支持助手', modelName: 'gpt-4o-mini', dataSources: [{ name: '本地知识库', status: 'healthy' }], taskPlanner: { status: 'ready', source: 'embedded_model' } },
    completedSteps: ['分析客户场景', '检索资料与证据'],
    pendingSteps: ['生成输出', '保存历史任务'],
    hasOutput: false,
  },
  {
    taskId: 't-draft',
    taskTitle: '备用：新客户初步评估',
    taskType: 'full_workflow',
    status: 'draft',
    recentStep: '未开始',
    assistantName: '—',
    updatedAt: '2026-04-27 09:00',
    taskGoal: '备用评估框架。',
    planVersions: [makePlanVersion('t-draft', 'v1', '初始计划')],
    evidencePackVersions: [],
    outputVersions: [],
    analysisSummary: '',
    evidenceSummary: '',
    risks: [],
    executionContext: { assistantName: '默认销售支持助手', modelName: 'gpt-4o-mini', dataSources: [{ name: '本地知识库', status: 'healthy' }], taskPlanner: { status: 'ready', source: 'embedded_model' } },
    hasOutput: false,
  },
  {
    taskId: 't-insufficient-done',
    taskTitle: '快速分析某客户需求',
    taskType: 'customer_analysis',
    status: 'completed',
    recentStep: 'Analysis 完成（证据不足）',
    assistantName: '默认销售支持助手',
    updatedAt: '2026-04-28 09:30',
    taskGoal: '快速分析客户需求。',
    planVersions: [makePlanVersion('t-insufficient-done', 'v1', '初始计划')],
    evidencePackVersions: [],
    outputVersions: [makeOutputVersion('t-insufficient-done', 'v1', '证据不足·首次生成')],
    analysisSummary: '分析完成：通用销售场景，缺少客户具体信息。',
    evidenceSummary: '证据不足：缺少客户公司全称和最近沟通记录。',
    risks: [{ level: 'warning', title: '证据不足', description: '缺少客户公司全称和最近沟通记录。' }],
    executionContext: { assistantName: '默认销售支持助手', modelName: 'gpt-4o-mini', dataSources: [{ name: '本地知识库', status: 'degraded' }], taskPlanner: { status: 'ready', source: 'embedded_model' } },
    completedSteps: ['分析客户场景', '生成输出', '保存历史任务'],
    pendingSteps: [],
    hasOutput: true,
  },
];
